### ISSUE TITLE
Bug: Can't cut Raw Book Wyrm on the Cutting Board using Tetra knives

### ISSUE THREAD

**Issue by YaibaToKen** [Lykrast/BookWyrms#3]
Despite being able to cut all other meats with Tetra knives (tetracelium adds integration with Farmer's Delight for Tetra), I am not able to cut Raw Book Wyrm.
Apparently a dummy recipe is needed, using `item.tetracelium.dummy_knife_blade` as the cutting tool.

**Comment by Lykrast** [comment]
This is not documented anywhere on Tetracelium's page and it doesn't have a wiki or source code to check for how it's expected to be done (and I'm not joining a discord to ask for clarification). Did they not do it by adding their knives to `forge:tools/knives`? (the tag checked by my compat recipe and the original Farmer's Delight ones)

**Comment by YaibaToKen** [comment]
I'm not sure, but I'll look through the mod a bit further as well as ask on their discord and get back to you.

**Comment by YaibaToKen** [comment]
Closing this as the problem lies in tetracelium instead.
